language: c++

sudo: enabled

matrix:
  include:
    - name: CUDA
      env:
      - UBUNTU_VERSION=ubuntu2004
      dist: focal

before_install:
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/cuda-ubuntu2004.pin
  - sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
  - sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub
  - sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /"
  - sudo apt-get update
  - sudo apt-get -y install cuda
  
script:
- bash install.sh -c -g
