language: c++

sudo: enabled

matrix:
  include:
    - name: CUDA
      env:
      - UBUNTU_VERSION=ubuntu2204
      dist: jammy

before_install:
- wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/cuda-keyring_1.0-1_all.deb
- sudo dpkg -i cuda-keyring_1.0-1_all.deb
- sudo apt-get update
- sudo apt-get -y install cuda
  
script:
- bash install.sh -c -g
